import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import { ImageKitProvider } from "@imagekit/next";
import ImageKitProviderWrapper from "./providers/ImageKitProviderWrapper";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({ headers: await headers() });
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <ImageKitProviderWrapper>
          <div className="relative min-h-screen overflow-hidden">
            {/* Amber Glow Background */}
            <div
              className="absolute inset-0 z-0"
              style={{
                backgroundImage:
                  "radial-gradient(125% 125% at 50% 90%, #ffffff 40%, #f59e0b 100%)",
                backgroundSize: "100% 100%",
              }}
            />
            {/* Main Content */}
            <div className="relative z-10 flex flex-col min-h-screen">
              <Navbar session={session} />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </div>
          <Toaster position="top-center" richColors />
        </ImageKitProviderWrapper>
      </body>
    </html>
  );
}
